### ISSUE TITLE
Add option to parse also plain-text emails without “markup=markdown"

### ISSUE THREAD

**Issue by xplosionmind** [dgileadi/thunderbird-render-markdown#2]
Since almost no email client supports appending `markup=markdown` to `Content-Type`, I think it should be possible to let users choose if they want to pass to this extensions also basic `text/plain` emails.

**Comment by dgileadi** [comment]
That's a good idea. I'll look at adding that option.

This extension works well for my narrow use case (reading newsgroup posts from [the DLang newsgroup](https://forum.dlang.org/help#about) which are sent with `markup=markdown`) so I hadn't considered turning it on for all `text/plain` messages. It makes good sense to have that option, though.

**Comment by dgileadi** [comment]
Published version 1.1.0 with the new option. It also now defaults to applying to all `text/plain` messages.
