### ISSUE TITLE
add feature to toggle rendering of currently viewed message

### ISSUE THREAD

**Issue by bollejansson** [dgileadi/thunderbird-render-markdown#4]
Some `text/plain` messages can look pretty messy when being rendered as markdown.

I would love to see a feature that toggles markdown rendering for the currently viewed message.
Maybe by adding an (optional) button to the mail header toolbar?

**Comment by dgileadi** [comment]
I wasn't able to figure out how to make an optional toolbar button, but I did add a context menu item to toggle this. It'll be available in 1.2.0.
